### ISSUE TITLE
panic on embedded struct pointer that implements Unmarshaler

### ISSUE THREAD

**Issue by segevfiner** [go-yaml/yaml#436]
### MWE
```go
package main

import (
	"fmt"

	"gopkg.in/yaml.v2"
)

type A struct {
	a string
}

func (a *A) UnmarshalYAML(unmarshal func(interface{}) error) error {
	if a == nil {
		fmt.Println("WTF?! a is nil")
	}

	return unmarshal(a)
}

type B struct {
	*A
}

var v = `a: "Hello, World!"`

func main() {
	var b B
	err := yaml.Unmarshal([]byte(v), &b)
	if err != nil {
		panic(err)
	}
}
```

### Output
```
WTF?! a is nil
panic: reflect: reflect.Value.Set using unaddressable value [recovered]
	panic: reflect: reflect.Value.Set using unaddressable value [recovered]
	panic: reflect: reflect.Value.Set using unaddressable value
goroutine 1 [running]:
gopkg.in/yaml%2ev2.handleErr(0xc0000bded0)
	<snip>/go/src/gopkg.in/yaml.v2/yaml.go:249 +0x112
panic(0x52f800, 0xc0000642a0)
	/usr/local/go/src/runtime/panic.go:513 +0x1e6
gopkg.in/yaml%2ev2.handleErr(0xc0000bda30)
	<snip>/go/src/gopkg.in/yaml.v2/yaml.go:249 +0x112
panic(0x52f800, 0xc0000642a0)
	/usr/local/go/src/runtime/panic.go:513 +0x1e6
reflect.flag.mustBeAssignable(0x16)
```

### Analysis
First issue is here: https://github.com/go-yaml/yaml/blob/51d6538a90f86fe93ac480b35f37b2be17fef232/decode.go#L308-L311

`u` holds a `*B` that has `A` set to `nil`. Calling `UnmarshalYAML` on that interface calls it on the embedded `A` which is `nil`. 

### Versions
Golang 1.11.5
go-yaml v2 @ 51d6538a90f86fe93ac480b35f37b2be17fef232
Xubuntu 18.04.1 x64

**Comment by segevfiner** [comment]
Actually... looks like this fails with `encoding/json` too: https://play.golang.org/p/c6Q_ehlEHMQ :persevere:
