### ISSUE TITLE
Unmarshal yaml node with long foot comment panics

### ISSUE THREAD

**Issue by yinonavraham** [go-yaml/yaml#483]
Using: `gopkg.in/yaml.v3 v3.0.0-20190502103701-55513cacd4ae`

`yaml.Unmarshal(..)` panics when attempting to parse yaml content with a node which has a long foot comment. 
Some observations:
1. There is a specific length in which the operation panics.
1. The length depends also on the next node
1. Parsing long head comments succeeds. turning the long foot comment of one property to the head comment of the next property (just by adding a line break before the comment) makes parsing successful (but wrong...)

Below is a unit test for reproducing the issue. It first tries to unmarshal the yaml content with the long foot comment, but it panics. Then, just by removing one last character, parsing succeeds.

```go
package yaml_test

import (
	"github.com/stretchr/testify/assert"
	"gopkg.in/yaml.v3"
	"testing"
)

func TestYamlParseLongFootComment(t *testing.T) {
	yamlContent := `foo: "foo"
#1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
#1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
#1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
#1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
#1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
#1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
#1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
#1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
#1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
#1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
#1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
#1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
#1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
#1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
#1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
#123`

	assert.NotPanics(t, func() {
		node := yaml.Node{}
		err := yaml.Unmarshal([]byte(yamlContent), &node)
		assert.NoError(t, err)
		t.Log("Success!!")
	})

	assert.NotPanics(t, func() {
		node := yaml.Node{}
		err := yaml.Unmarshal([]byte(yamlContent[:len(yamlContent)-1]), &node)
		assert.NoError(t, err)
		t.Log("Success!! (but one character less...)")
	})
}
```

Test output:
```
=== RUN   TestYamlParseLongFootComment
--- FAIL: TestYamlParseLongFootComment (0.00s)
    yaml_parse_test.go:28: 
        	Error Trace:	yaml_parse_test.go:28
        	Error:      	func (assert.PanicTestFunc)(0x1461590) should not panic
        	            		Panic value:	runtime error: index out of range
        	Test:       	TestYamlParseLongFootComment
    yaml_parse_test.go:39: Success!! (but one character less...)
FAIL
```

Panic stack trace (running without `assert.NotPanics(...)`):
```
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 19 [running]:
testing.tRunner.func1(0xc0000ec500)
	<...>/go/1.12/libexec/src/testing/testing.go:830 +0x388
panic(0x14dfce0, 0x1963580)
	<...>/go/1.12/libexec/src/runtime/panic.go:522 +0x1b5
gopkg.in/yaml%2ev3.handleErr(0xc0000bff70)
	~/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20190502103701-55513cacd4ae/yaml.go:276 +0x9a
panic(0x14dfce0, 0x1963580)
	<...>/go/1.12/libexec/src/runtime/panic.go:522 +0x1b5
gopkg.in/yaml%2ev3.yaml_parser_update_buffer(0xc000146000, 0x601, 0x501)
	~/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20190502103701-55513cacd4ae/readerc.go:417 +0xb32
gopkg.in/yaml%2ev3.yaml_parser_scan_foot_comment(0xc000146000, 0x5, 0x0, 0x5, 0xc0000bf801)
	~/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20190502103701-55513cacd4ae/scannerc.go:2846 +0x921
gopkg.in/yaml%2ev3.yaml_parser_fetch_next_token.func1(0xc0000bf928, 0xc000146000, 0x5, 0x0, 0x5)
	~/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20190502103701-55513cacd4ae/scannerc.go:758 +0x8e
gopkg.in/yaml%2ev3.yaml_parser_fetch_next_token(0xc000146000, 0xc000088701)
	~/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20190502103701-55513cacd4ae/scannerc.go:838 +0x6d8
gopkg.in/yaml%2ev3.yaml_parser_fetch_more_tokens(0xc000146000, 0xc0001561b0)
	~/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20190502103701-55513cacd4ae/scannerc.go:680 +0x55
gopkg.in/yaml%2ev3.peek_token(0xc000146000, 0xc0001561b0)
	~/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20190502103701-55513cacd4ae/parserc.go:69 +0x81
gopkg.in/yaml%2ev3.yaml_parser_parse_block_mapping_value(0xc000146000, 0xc000146270, 0xc0000a8008)
	~/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20190502103701-55513cacd4ae/parserc.go:832 +0xcf
gopkg.in/yaml%2ev3.yaml_parser_state_machine(0xc000146000, 0xc000146270, 0x3)
	~/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20190502103701-55513cacd4ae/parserc.go:190 +0x2ad
gopkg.in/yaml%2ev3.yaml_parser_parse(0xc000146000, 0xc000146270, 0x1044cd2)
	~/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20190502103701-55513cacd4ae/parserc.go:125 +0x91
gopkg.in/yaml%2ev3.(*parser).peek(0xc000146000, 0xc0000a8008)
	~/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20190502103701-55513cacd4ae/decode.go:102 +0x42
gopkg.in/yaml%2ev3.(*parser).parse(0xc000146000, 0x0)
	~/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20190502103701-55513cacd4ae/decode.go:141 +0x3d
gopkg.in/yaml%2ev3.(*parser).parseChild(0xc000146000, 0xc00013c140, 0xc00013c1e0)
	~/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20190502103701-55513cacd4ae/decode.go:184 +0x2f
gopkg.in/yaml%2ev3.(*parser).mapping(0xc000146000, 0x9)
	~/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20190502103701-55513cacd4ae/decode.go:266 +0x12a
gopkg.in/yaml%2ev3.(*parser).parse(0xc000146000, 0x0)
	~/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20190502103701-55513cacd4ae/decode.go:147 +0x187
gopkg.in/yaml%2ev3.(*parser).parseChild(0xc000146000, 0xc00013c0a0, 0x0)
	~/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20190502103701-55513cacd4ae/decode.go:184 +0x2f
gopkg.in/yaml%2ev3.(*parser).document(0xc000146000, 0x3)
	~/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20190502103701-55513cacd4ae/decode.go:193 +0x94
gopkg.in/yaml%2ev3.(*parser).parse(0xc000146000, 0x1577810)
	~/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20190502103701-55513cacd4ae/decode.go:151 +0x142
gopkg.in/yaml%2ev3.unmarshal(0xc00013e000, 0x609, 0x700, 0x1504e40, 0xc00013c000, 0x700, 0x0, 0x0)
	~/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20190502103701-55513cacd4ae/yaml.go:161 +0x258
gopkg.in/yaml%2ev3.Unmarshal(...)
	~/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20190502103701-55513cacd4ae/yaml.go:89
<...>.TestYamlParseLongFootComment(0xc0000ec500)
	<...>/yaml_parse_test.go:30 +0x9b
testing.tRunner(0xc0000ec500, 0x1577b28)
	<...>/go/1.12/libexec/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	<...>/go/1.12/libexec/src/testing/testing.go:916 +0x357
```

**Comment by niemeyer** [comment]
20190502 is not current. Please update and let us know how it goes. Thanks for the report.

**Comment by yinonavraham** [comment]
Tested with version `v3.0.0-20190709130402-674ba3eaed22` and it works like a charm.
Thanks!!
