### ISSUE TITLE
Panic in yaml_parser_split_stem_comment when peek_token returns nil

### ISSUE THREAD

**Issue by howardjohn** [go-yaml/yaml#768]
```go
func yaml_parser_split_stem_comment(parser *yaml_parser_t, stem_len int) {
	if stem_len == 0 {
		return
	}

	token := peek_token(parser)
	if token.typ != yaml_BLOCK_SEQUENCE_START_TOKEN && token.typ != yaml_BLOCK_MAPPING_START_TOKEN {
		return
	}
```

Is not safe; when peek_token returns `nil` we will panic.

Reproducer: 
[repro.txt](https://github.com/go-yaml/yaml/files/6879901/repro.txt)

```
2021-07-26T16:45:23.415125Z	error	Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 15 [running]:
istio.io/istio/pilot/pkg/util/runtime.LogPanic(0x56b7240, 0x7a7c360)
	/usr/local/google/home/howardjohn/go/src/istio.io/istio/pilot/pkg/util/runtime/runtime.go:29 +0x8d
istio.io/istio/tests/fuzz.runRegressionTest.func1.1(0xc00015cc76, 0x10, 0xc0010c0d80)
	/usr/local/google/home/howardjohn/go/src/istio.io/istio/tests/fuzz/regression_test.go:55 +0x199
panic(0x56b7240, 0x7a7c360)
	/usr/local/google/home/howardjohn/sdk/go1.16/src/runtime/panic.go:971 +0x4c7
gopkg.in/yaml%2ev3.handleErr(0xc000c36b50)
	/usr/local/google/home/howardjohn/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20210107192922-496545a6307b/yaml.go:294 +0x112
panic(0x56b7240, 0x7a7c360)
	/usr/local/google/home/howardjohn/sdk/go1.16/src/runtime/panic.go:971 +0x4c7
gopkg.in/yaml%2ev3.yaml_parser_split_stem_comment(0xc00107f800, 0x1)
	/usr/local/google/home/howardjohn/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20210107192922-496545a6307b/parserc.go:789 +0x67
gopkg.in/yaml%2ev3.yaml_parser_parse_indentless_sequence_entry(0xc00107f800, 0xc00107fab0, 0x0)
	/usr/local/google/home/howardjohn/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20210107192922-496545a6307b/parserc.go:751 +0xd1
gopkg.in/yaml%2ev3.yaml_parser_state_machine(0xc00107f800, 0xc00107fab0, 0xc00107fa00)
	/usr/local/google/home/howardjohn/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20210107192922-496545a6307b/parserc.go:185 +0x32b
gopkg.in/yaml%2ev3.yaml_parser_parse(0xc00107f800, 0xc00107fab0, 0x0)
	/usr/local/google/home/howardjohn/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20210107192922-496545a6307b/parserc.go:129 +0xb6
gopkg.in/yaml%2ev3.(*parser).peek(0xc00107f800, 0xc000a2d900)
	/usr/local/google/home/howardjohn/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20210107192922-496545a6307b/decode.go:103 +0x85
gopkg.in/yaml%2ev3.(*parser).sequence(0xc00107f800, 0x0)
	/usr/local/google/home/howardjohn/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20210107192922-496545a6307b/decode.go:258 +0x1ba
gopkg.in/yaml%2ev3.(*parser).parse(0xc00107f800, 0x0)
	/usr/local/google/home/howardjohn/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20210107192922-496545a6307b/decode.go:154 +0x165
gopkg.in/yaml%2ev3.(*parser).parseChild(0xc00107f800, 0xc000a2cd20, 0x0)
	/usr/local/google/home/howardjohn/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20210107192922-496545a6307b/decode.go:194 +0x38
gopkg.in/yaml%2ev3.(*parser).mapping(0xc00107f800, 0x0)
	/usr/local/google/home/howardjohn/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20210107192922-496545a6307b/decode.go:285 +0x325
gopkg.in/yaml%2ev3.(*parser).parse(0xc00107f800, 0x0)
	/usr/local/google/home/howardjohn/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20210107192922-496545a6307b/decode.go:152 +0x1a5
gopkg.in/yaml%2ev3.(*parser).parseChild(0xc00107f800, 0xc000a2c960, 0x0)
	/usr/local/google/home/howardjohn/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20210107192922-496545a6307b/decode.go:194 +0x38
gopkg.in/yaml%2ev3.(*parser).document(0xc00107f800, 0x0)
	/usr/local/google/home/howardjohn/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20210107192922-496545a6307b/decode.go:203 +0xc5
gopkg.in/yaml%2ev3.(*parser).parse(0xc00107f800, 0x0)
	/usr/local/google/home/howardjohn/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20210107192922-496545a6307b/decode.go:156 +0xa5
gopkg.in/yaml%2ev3.unmarshal(0xc000b6a789, 0x42, 0x94, 0x59428a0, 0xc000a2c6e0, 0x1a14300, 0x0, 0x0)
	/usr/local/google/home/howardjohn/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20210107192922-496545a6307b/yaml.go:161 +0x125
gopkg.in/yaml%2ev3.Unmarshal(0xc000b6a789, 0x42, 0x94, 0x59428a0, 0xc000a2c6e0, 0x0, 0x0)
	/usr/local/google/home/howardjohn/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20210107192922-496545a6307b/yaml.go:89 +0x6a
istio.io/istio/galley/pkg/config/source/kube/inmemory.(*KubeSource).parseChunk(0xc000a02b90, 0xc000f11ee0, 0x0, 0x0, 0x1, 0xc000b6a789, 0x42, 0x94, 0x0, 0x0, ...)
	/usr/local/google/home/howardjohn/go/src/istio.io/istio/galley/pkg/config/source/kube/inmemory/kubesource.go:311 +0xc05
istio.io/istio/galley/pkg/config/source/kube/inmemory.(*KubeSource).parseContent(0xc000a02b90, 0xc000f11ee0, 0x0, 0x0, 0xc000086b40, 0x5c, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/google/home/howardjohn/go/src/istio.io/istio/galley/pkg/config/source/kube/inmemory/kubesource.go:224 +0x853
istio.io/istio/galley/pkg/config/source/kube/inmemory.(*KubeSource).ApplyContent(0xc000a02b90, 0x0, 0x0, 0xc000086b40, 0x5c, 0x0, 0x0)
	/usr/local/google/home/howardjohn/go/src/istio.io/istio/galley/pkg/config/source/kube/inmemory/kubesource.go:151 +0x131
```

**Comment by niemeyer** [comment]
Dup of https://github.com/go-yaml/yaml/issues/665 as @itchyny noted. Fixed and commented there.
