### ISSUE TITLE
Panic while parsing "#\n-\n{"

### ISSUE THREAD

**Issue by tcarzverey** [go-yaml/yaml#855]
I was testing app with fuzzing and this error occured:
```
Error message:
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4c4698]

goroutine 1 [running]:
gopkg.in/yaml%2ev3.handleErr(0xc00004dec8)
        /home/lev/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0/yaml.go:294 +0x6d
panic({0x4eb9c0, 0x5b9270})
        /usr/local/go/src/runtime/panic.go:838 +0x207
gopkg.in/yaml%2ev3.yaml_parser_split_stem_comment(0xc000040c00, 0x1)
        /home/lev/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0/parserc.go:789 +0x38
gopkg.in/yaml%2ev3.yaml_parser_parse_block_sequence_entry(0xc000040c00, 0xc000040eb0, 0x5?)
        /home/lev/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0/parserc.go:703 +0x1e5
gopkg.in/yaml%2ev3.yaml_parser_state_machine(0x0?, 0x0?)
        /home/lev/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0/parserc.go:179 +0x13b
gopkg.in/yaml%2ev3.yaml_parser_parse(0xc0001063c0?, 0x4fe5ab?)
        /home/lev/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0/parserc.go:129 +0x8c
gopkg.in/yaml%2ev3.(*parser).peek(0xc000040c00)
        /home/lev/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0/decode.go:106 +0x30
gopkg.in/yaml%2ev3.(*parser).sequence(0xc000040c00)
        /home/lev/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0/decode.go:261 +0x110
gopkg.in/yaml%2ev3.(*parser).parse(0xc000040c00)
        /home/lev/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0/decode.go:157 +0xe7
gopkg.in/yaml%2ev3.(*parser).parseChild(...)
        /home/lev/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0/decode.go:197
gopkg.in/yaml%2ev3.(*parser).document(0xc000040c00)
        /home/lev/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0/decode.go:206 +0x7d
gopkg.in/yaml%2ev3.(*parser).parse(0xc000040c00)
        /home/lev/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0/decode.go:159 +0xab
gopkg.in/yaml%2ev3.unmarshal({0xc0000145d8, 0x5, 0x8}, {0x4f0d80?, 0xc00006e540}, 0x60?)
        /home/lev/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0/yaml.go:161 +0x306
gopkg.in/yaml%2ev3.Unmarshal(...)
        /home/lev/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0/yaml.go:89
exit status 2
```
Can be reproduced with:
```
text := "#\n-\n{"
yaml.Unmarshal([]byte(text), nil)
```

**Comment by itchyny** [comment]
Likely duplicate of #665, #744, #768.

**Comment by niemeyer** [comment]
> Likely duplicate of https://github.com/go-yaml/yaml/issues/665 ...

Indeed. Fixed and commented there.
