### ISSUE TITLE
v3: panic (hash of unhashable type map)

### ISSUE THREAD

**Issue by dsp25no** [go-yaml/yaml#932]
Minimal example of the panic(https://go.dev/play/p/r5lt0EVJAxy):

```golang
package main

import (
	"gopkg.in/yaml.v3"
)

func main() {
	var t interface{}
	yaml.Unmarshal([]byte("?\n<<:\n ? 0:"), &t)
}
```

Output:
```
panic: runtime error: hash of unhashable type map[interface {}]interface {} [recovered]
	panic: runtime error: hash of unhashable type map[interface {}]interface {}

goroutine 1 [running]:
gopkg.in/yaml%2ev3.handleErr(0xc000051ee8)
	/tmp/gopath584265875/pkg/mod/gopkg.in/yaml.v3@v3.0.1/yaml.go:294 +0x6d
panic({0x4ee980, 0xc000014430})
	/usr/local/go-faketime/src/runtime/panic.go:884 +0x212
gopkg.in/yaml%2ev3.(*decoder).mapping(0xc0001095e0, 0xc0000006e0, {0x4ee200?, 0xc000016630?, 0x7f275d3ed1a0?})
	/tmp/gopath584265875/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:835 +0x898
gopkg.in/yaml%2ev3.(*decoder).unmarshal(0xc0001095e0, 0xc0000006e0, {0x4ee200?, 0xc000016630?, 0x7f275d3e4108?})
	/tmp/gopath584265875/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:510 +0x3eb
gopkg.in/yaml%2ev3.(*decoder).merge(0xc0001095e0, 0xc000000460?, 0xc0000006e0, {0x4ee200?, 0xc000016630?, 0x194?})
	/tmp/gopath584265875/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:973 +0x245
gopkg.in/yaml%2ev3.(*decoder).mapping(0xc0001095e0, 0xc000000460, {0x4ecca0?, 0xc000014370?, 0x0?})
	/tmp/gopath584265875/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:856 +0xb94
gopkg.in/yaml%2ev3.(*decoder).unmarshal(0xc0001095e0, 0xc000000460, {0x4ecca0?, 0xc000014370?, 0x0?})
	/tmp/gopath584265875/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:510 +0x3eb
gopkg.in/yaml%2ev3.(*decoder).document(0x0?, 0x0?, {0x4ecca0?, 0xc000014370?, 0xc000044c00?})
	/tmp/gopath584265875/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:527 +0x5b
gopkg.in/yaml%2ev3.(*decoder).unmarshal(0xc0001095e0, 0xc0000003c0, {0x4ecca0?, 0xc000014370?, 0x0?})
	/tmp/gopath584265875/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:498 +0x42d
gopkg.in/yaml%2ev3.unmarshal({0xc00001c590, 0xb, 0xb}, {0x4e6b60?, 0xc000014370}, 0xe0?)
	/tmp/gopath584265875/pkg/mod/gopkg.in/yaml.v3@v3.0.1/yaml.go:167 +0x426
gopkg.in/yaml%2ev3.Unmarshal(...)
	/tmp/gopath584265875/pkg/mod/gopkg.in/yaml.v3@v3.0.1/yaml.go:89
main.main()
	/tmp/sandbox3232958416/prog.go:9 +0x71

Program exited.
```

**Comment by quenbyako** [comment]
What behavior did you expect to have? 🤨

**Comment by niemeyer** [comment]
Indeed no input should result in a panic if the code itself is fine. I'll look into it next week, thanks for the report.

**Comment by ghost** [comment]
I believe https://github.com/go-yaml/yaml/issues/895 describes the same problem.

**Comment by braydonk** [comment]
It was panicking because it wasn't checking that the reflected type was comparable. I provided a PR to suggest a fix.
