### ISSUE TITLE
Private embeded structs cause a panic

### ISSUE THREAD

**Issue by EduardGomezEscandell** [go-yaml/yaml#944]
When a struct with a private embeded type is unmarshaled, a panic occurs. Here is the smallest reproducible example I could make.

```go
package main

import "gopkg.in/yaml.v3"

type embeddedType struct{}

type DemoType struct {
	embeddedType
}

func main() {
	var input DemoType
	yaml.Marshal(input)
}
```

Tested with `go version go1.20 linux/amd64` and `go version go1.20 windows/amd64` with `gopkg.in/yaml.v3 v3.0.1`

**Comment by EduardGomezEscandell** [comment]
Here is the trace in case it is useful:
```
$ go run main.go 
panic: reflect.Value.Interface: cannot return value obtained from unexported field or method [recovered]
        panic: reflect.Value.Interface: cannot return value obtained from unexported field or method

goroutine 1 [running]:
gopkg.in/yaml%2ev3.handleErr(0xc000069ca0)
        /home/edu/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/yaml.go:294 +0x6d
panic({0x4d7620, 0x513bc8})
        /usr/local/go/src/runtime/panic.go:884 +0x213
reflect.valueInterface({0x4db4e0?, 0x5ddff0?, 0x0?}, 0x20?)
        /usr/local/go/src/reflect/value.go:1491 +0xd8
reflect.Value.Interface(...)
        /usr/local/go/src/reflect/value.go:1480
gopkg.in/yaml%2ev3.(*encoder).marshal(0xc000018610?, {0x0, 0x0}, {0x4db4e0?, 0x5ddff0?, 0x0?})
        /home/edu/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/encode.go:117 +0x1dd
gopkg.in/yaml%2ev3.(*encoder).structv.func1()
        /home/edu/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/encode.go:235 +0x268
gopkg.in/yaml%2ev3.(*encoder).mappingv(0xc00005cc00, {0x0?, 0x0}, 0xc000069a48)
        /home/edu/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/encode.go:265 +0x146
gopkg.in/yaml%2ev3.(*encoder).structv(0xc00005cc00, {0x0, 0x0}, {0x4dd820?, 0x5ddff0?, 0x0?})
        /home/edu/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/encode.go:219 +0xef
gopkg.in/yaml%2ev3.(*encoder).marshal(0xc00005cc00?, {0x0, 0x0}, {0x4dd820?, 0x5ddff0?, 0xc000069c20?})
        /home/edu/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/encode.go:168 +0x93d
gopkg.in/yaml%2ev3.(*encoder).marshalDoc(0xc00005cc00, {0x0, 0x0}, {0x4dd820?, 0x5ddff0?, 0xc000014130?})
        /home/edu/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/encode.go:105 +0x12b
gopkg.in/yaml%2ev3.Marshal({0x4dd820?, 0x5ddff0})
        /home/edu/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/yaml.go:222 +0x389
main.main()
        /home/edu/break_yaml/main.go:15 +0x27
exit status 2
```

**Comment by saddit** [comment]
Adding tag `yaml:'-'` can fix it
